name: Auto Minify JS and CSS Files

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]
    paths: 
      - 'assets/**/*.js'
      - 'assets/**/*.css'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
  
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: 'assets'

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate minified JS and CSS files"